version: "3"

volumes:
        data:
                driver_opts:
                        type: none
                        device: /path/to/nextcloud/data
                        o: bind
        database:
                driver_opts:
                        type: none
                        device: /path/to/nextcloud/database
                        o: bind

networks:
        default:
                external:
                        name: proxy-tier

services:
  nextcloud_app:
          build: ./nextcloud
          container_name: nextcloud_app
          depends_on:
                  - nextcloud_db
          links:
                  - nextcloud_db
          volumes:
                  - data:/var/www/html
          environment:
                  VIRTUAL_PORT: 80
                  VIRTUAL_NETWORK: proxy-tier
                  VIRTUAL_HOST: cloud.example.tld
                  LETSENCRYPT_HOST: cloud.example.tld
                  LETSENCRYPT_EMAIL: mail@example.tld
          restart: always

  nextcloud_db:
          image: mariadb:10
          container_name: nextcloud_db
          volumes:
                  - database:/var/lib/mysql
                  - ./conf/mariadb.cnf:/etc/mysql/conf.d/mariadb.cnf:ro
          environment:
                  MYSQL_ROOT_PASSWORD: secret
                  MYSQL_USER: nextcloud
                  MYSQL_PASSWORD: secret
                  MYSQL_DATABASE: nextcloud
          restart: always
