version: "3"

volumes:
        data:
                driver_opts:
                        type: none
                        device: /path/to/typo3/data
                        o: bind
        database:
                driver_opts:
                        type: none
                        device: /path/to/typo3/database
                        o: bind

networks:
        default:
                external:
                        name: proxy-tier

services:
        typo3_app:
                image: martinhelmich/typo3:9.5
                container_name: typo3_app
                depends_on:
                        - typo3_db
                links:
                        - typo3_db
                volumes:
                        - data:/var/www/html
                environment:
                        VIRTUAL_PORT: 80
                        VIRTUAL_NETWORK: proxy-tier
                        VIRTUAL_HOST: www.example.tld,example.tld
                        LETSENCRYPT_HOST: www.example.tld,example.tld
                        LETSENCRYPT_EMAIL: mail@example.tld
                restart: always

        typo3_db:
                image: mariadb:10
                container_name: typo3_db
                volumes:
                        - database:/var/lib/mysql
                        - ./conf/mariadb.cnf:/etc/mysql/conf.d/mariadb.cnf:ro
                environment:
                        MYSQL_ROOT_PASSWORD: secret
                        MYSQL_USER: typo3
                        MYSQL_PASSWORD: secret
                        MYSQL_DATABASE: typo3
                restart: always
